---

- hosts: localhost
  connection: local
  python_interpreter: python
  become: true
  roles:
    - base
    - users
    - software
  when: ansible_distribution == "Kali" and ansible_os_family == "Debian"
